# ~/.bashrc
#


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Enable extended globbing
shopt -s extglob

# Stops from accidentally overwriting a file using >
set -o noclobber

# Fuzzy find utils
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash


########## Exports ##########
#export LS_COLORS="$(vivid -m 8-bit generate solarized-dark)"
export EDITOR="micro"

#export LUA_PATH='/usr/share/lua/5.4/?.lua;/usr/share/lua/5.4/?/init.lua;/usr/lib/lua/5.4/?.lua;/usr/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua;/home/conor/.luarocks/share/lua/5.4/?.lua;/home/conor/.luarocks/share/lua/5.4/?/init.lua'
#export LUA_CPATH='/usr/lib/lua/5.4/?.so;/usr/lib/lua/5.4/loadall.so;./?.so;/home/conor/.luarocks/lib/lua/5.4/?.so'
export PATH="$PATH:/home/conor/.luarocks/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
export PATH="$PATH:/home/conor/.local/bin"
#export PATH="$PATH:/home/conor/.dotnet/tools"

########## Aliases ##########
alias ls='ls -Ap --group-directories-first --color=auto'
alias py='python3'
alias pgrep='pgrep -ai'
alias lua='lua5.3'

page_man() {
    man "$1" | w3m
}
alias man=page_man

alias hostname='cat /etc/hostname'


########## Prompts ###########

# include .bashrc_prompt if it exists
[ -f ~/.dotfiles/bash/bashrc_prompt.sh ] && . ~/.dotfiles/bash/bashrc_prompt.sh

# eval "$(starship init bash)"
